#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Merge Part1+Part2 zh-TW translations into Strings.zh-TW.resx"""
import html

# Part 1 (entries 1-694): values are XML-entity-encoded; html.unescape() decodes them
PART1 = {
"AboutAbout":"關於(&amp;T) {0}",
"AboutConfigurationVersion":"設定版本：{0}",
"AboutCopyright":"著作權所有 © .NET Foundation。保留一切權利。",
"AboutVersion":"{0}",
"AccountPanel":"帳號",
"AddButton":"新增(&amp;D)...",
"AddButton2":"新增(&amp;A)",
"AdvancedBlogOverride":"其他部落格設定",
"AdvancedDefault":"預設 ({0})",
"AdvancedEmbedTags":"Embed 標籤(&amp;E)：",
"AdvancedName":"進階",
"AdvancedScripts":"Script 指令碼(&amp;S)：",
"AdvancedText":"為你的部落格文章選擇其他編碼類型。預設為 UTF-8。",
"AdvancedTransport":"字元集",
"AdvancedXHTMLDefault":"預設 ({0})",
"AdvancedXHTMLGroupName":"標記語言",
"AdvancedXHTMLLabel":"選擇使用 HTML 或 XHTML 作為標記語言。預設為 HTML。",
"Alignment":"對齊",
"AlignMenuItem":"對齊(&amp;A)",
"AllFilesFilterString":"所有檔案 (*.*)",
"AllowAutoUpdate":"自動更新(&amp;U)帳號資訊（類別、連結、功能及服務供應商延伸模組）",
"AllowProviderExtensions":"允許部落格服務供應商延伸模組(&amp;B)（按鈕會新增到功能區帳號索引標籤的捷徑群組）",
"AltTextEditorTitle":"替代文字",
"Appearance":"外觀",
"ApplyButton":"套用(&amp;A)",
"AutoRecoverDialogButtonAskLater":"稍後詢問(&amp;A)",
"AutoRecoverDialogButtonDiscard":"永久捨棄變更(&amp;D)",
"AutoRecoverDialogButtonRecover":"立即復原變更（建議）(&amp;R)",
"AutoRecoverDialogContent":"{0} 上次使用時沒有正常關閉。有未儲存的變更可供復原。您要立即復原這些變更嗎？",
"AutoRecoverDialogInstruction":"復原未儲存的變更？",
"AutoreplaceEmoticons":"以表情符號圖案取代文字表情符號(&amp;E)",
"AutoreplaceFormTitle":"自動取代",
"AutoreplaceOtherChars":"取代其他特殊字元(&amp;P)",
"AutoreplacePrefererencesPanel":"自動取代",
"AutoreplaceReplacementValue":"取代值：",
"AutoreplaceSmartQuotes":"以「彎引號」取代「直引號」(&amp;Q)",
"AutoreplaceTypographic":"以破折號（—）取代連字號（--）(&amp;Y)",
"AutoreplaceWordorPhrase":"單字或片語：",
"BCEAuthenticationMessage":"請檢查您的使用者名稱和密碼。\n\n{0} - {1}",
"BCEAuthenticationTitle":"帳號登入失敗",
"BCEConnectionErrorMessage":"嘗試連線到下列位址的部落格時發生錯誤：\n\n{0}\n\n{1}",
"BCEConnectionErrorTitle":"網路連線錯誤",
"BCEFileIOMessage":"存取檔案 {0} 時發生未預期的錯誤\n\n{1} - {2}",
"BCEFileIOTitle":"檔案存取錯誤",
"BCEFileTransferConnectingToDestination":"正在連線到檔案目的地",
"BCEFileTransferDisconnectingFromDestination":"正在中斷與檔案目的地的連線",
"BCEFileTransferMessage":"執行 {0} 時發生錯誤\n\n({1}) {2}",
"BCEFileTransferTitle":"檔案傳輸錯誤",
"BCEFileTransferTransferringFile":"正在傳輸檔案 {0}",
"BCEFileUploadNotSupportedMessage":"此部落格不支援檔案上傳。請在嘗試發佈含有附加圖片或檔案的文章之前，先設定此部落格的檔案上傳功能。",
"BCEFileUploadNotSupportedTitle":"不支援檔案上傳",
"BCEHttpErrorMessage":"伺服器回報下列網址發生錯誤：\n\n{0}\n\n{1}",
"BCEHttpErrorTitle":"伺服器錯誤",
"BCEInvalidServerResponseMessage":"從部落格伺服器收到的 {0} 方法回應無效：\n\n{1}",
"BCEInvalidServerResponseTitle":"無效的伺服器回應",
"BCEInvalidPostIdMessage":"部落格伺服器無法識別文章 ID。文章可能已從伺服器刪除，或文章 ID 遺失。請嘗試改為建立新文章。\n\n{0} {1}",
"BCEInvalidPostIdTitle":"無效的文章 ID",
"BCEMethodUnsupportedMessage":"部落格服務不支援 {0} 方法。",
"BCEMethodUnsupportedTitle":"不支援的方法",
"BCENetworkIOMessage":"執行 {0} 時發生未預期的資料傳輸例外狀況\n\n{1} - {2}",
"BCENetworkIOTitle":"資料傳輸例外狀況",
"BCEOperationCancelledMessage":"作業已取消。",
"BCEOperationCancelledTitle":"作業已取消",
"BCEPostAsDraftUnsupportedMessage":"此伺服器不支援以草稿形式發佈文章。",
"BCEPostAsDraftUnsupportedTitle":"不支援以草稿發佈",
"BCEPostUrlNotFoundMessage":"找不到部落格的文章網址：\n\n{0}\n\n{1}",
"BCEPostUrlNotFoundTitle":"找不到部落格文章網址",
"BCEProviderMessage":"發生伺服器錯誤 {0}\n\n{1}",
"BCEProviderTitle":"部落格伺服器發生問題",
"Beta":"Beta",
"Beta1DayRemaining":"剩餘 1 天",
"BetaDaysRemaining":"剩餘 {0} 天",
"BetaExpiredAskLater":"稍後詢問(&amp;A)",
"BetaExpiredDialogTitle":"到期",
"BetaExpiredDownloadNow":"立即下載(&amp;D)",
"BetaExpiredMessage":"此版本的 {0} 已到期。請下載並安裝較新的版本。",
"BetaExpiredTitle":"已到期",
"BetaRemainingMessage":"此版本的 {0} 將於 {1} 到期。請下載並安裝較新的版本。",
"Blog":"部落格",
"Blog_Option_Not_Supported":"不支援",
"Blog_Option_Supported":"支援",
"Blog_Option_Unknown":"不明",
"BlogCategoryNone":"無",
"BloggerAccountDeleted":"使用者帳號已被刪除。",
"BloggerAccountDisabled":"使用者帳號已被停用。",
"BloggerBadAuthentication":"使用者名稱或密碼無法識別。",
"BloggerGenericError":"發生錯誤：{0}",
"BloggerImageAlbumDescription":"此相簿用於儲存 Open Live Writer 發佈的部落格文章中的圖片。",
"BloggerNotVerified":"帳號電子郵件地址尚未驗證。使用者必須直接存取其 Google 帳號以解決此問題，之後才能使用非 Google 應用程式登入。",
"BloggerServiceUnavailable":"服務目前無法使用；請稍後再試。",
"BloggerTermsNotAgreed":"使用者尚未同意條款。使用者必須直接存取其 Google 帳號以解決此問題，之後才能使用非 Google 應用程式登入。",
"BloggerUnknown":"錯誤不明或未指定；要求包含無效的輸入或格式不正確。",
"BlogPluginsDescription":"選取您要使用的外掛程式，並變更其啟動順序。",
"BlogServiceNames":"TypePad 及其他",
"BrightnessAdjust":"對比",
"BrightnessBrightness":"亮度(&amp;B)：",
"BrightnessContrast":"對比(&amp;C)：",
"BrowseForFile":"瀏覽檔案",
"BrowserMiniFormProgress":"正在擷取...",
"BytesFormat":"{0} 位元組",
"CancelButton":"取消",
"Canceling":"正在取消...",
"CantSignIn":"因發生錯誤而無法登入",
"Capabilities":"部落格服務功能(&amp;C)：",
"CapabilityAuthor":"作者",
"CapabilityAutoUpdate":"自動更新",
"CapabilityCategories":"類別",
"CapabilityCategoriesInline":"類別（行內）",
"CapabilityCategoryNameLimit":"類別名稱長度限制",
"CapabilityCategoryScheme":"類別配置",
"CapabilityCharacterSet":"編碼",
"CapabilityCommentPolicy":"留言原則",
"CapabilityCustomPublishDate":"自訂發佈日期",
"CapabilityCustomPublishDateUpdate":"更新發佈日期",
"CapabilityDefaultView":"預設檢視",
"CapabilityEmbeds":"內嵌",
"CapabilityEmptyTitles":"空白標題",
"CapabilityExcerpt":"摘要",
"CapabilityExtendedEntries":"延伸項目",
"CapabilityFileUpload":"檔案上傳",
"CapabilityHierarchicalCategories":"階層式類別",
"CapabilityHtmlTitles":"HTML 標題",
"CapabilityKeywordRetrieval":"關鍵字擷取",
"CapabilityKeywords":"關鍵字",
"CapabilityMultipleCategories":"多重類別",
"CapabilityNewCategories":"新類別",
"CapabilityNewCategoriesInline":"新類別（行內）",
"CapabilityPageOrder":"頁面排序",
"CapabilityPageParent":"頁面上層",
"CapabilityPages":"頁面",
"CapabilityPassword":"密碼",
"CapabilityPostDraftToServer":"將草稿發佈至伺服器",
"CapabilityPostTitleLengthLimit":"標題長度限制",
"CapabilityRequiresXHTML":"需要 XHTML",
"CapabilityScripts":"指令碼",
"CapabilitySendTrackbacks":"傳送引用通知",
"CapabilitySlug":"文章別名",
"CapabilityTemplateIsRTL":"範本為由右至左",
"CapabilityTrackbackPolicy":"引用通知原則",
"CapabilityValueNoLimit":"(無限制)",
"CapabilityValueNormal":"一般",
"CapabilityValueWebLayout":"網頁版面配置",
"CapabilityValueWebPreview":"網頁預覽",
"CategoryAdd":"新增類別",
"CategoryCategoryName":"類別名稱",
"CategoryControlCategories":"類別：{0}",
"CategoryControlCategory":"類別：{0}",
"CategoryControlNoCategories":"(無)",
"CategoryControlNoCategories2":"(無類別)",
"CategoryControlSetCategories":"設定類別",
"CategoryControlSetCategory":"設定類別",
"CategoryNoParent":"(無上層)",
"CategoryParentAccessible":"類別上層",
"CategoryRefreshList":"重新整理清單",
"CategoryRefreshListTooltip":"重新整理類別清單。",
"Cell":"儲存格",
"CellPropertiesTitle":"儲存格屬性",
"Cells":"儲存格",
"ChangeLiveClipboardHandlerCaption":"可以處理「{0}」的元件：",
"ChangeLiveClipboardHandlerComponent":"元件",
"ChangeLiveClipboardHandlerTitle":"變更格式處理常式",
"ChangeTextStyle":"變更文字樣式",
"CharCount":"字元數（含空格）",
"CharNoSpacesCount":"字元數（不含空格）",
"ClickToViewMap":"按一下可在 Live.com 上檢視此地圖",
"CloseButton":"關閉(&amp;C)",
"CloseButtonNoMnemonic":"關閉",
"CloseButtonTooltip":"關閉",
"ColorBlack":"黑色",
"ColorCharcoal":"炭灰色",
"ColorDarkGray":"深灰色",
"ColorEarthyBlue":"大地藍",
"ColorEarthyBrown":"大地棕",
"ColorEarthyGreen":"大地綠",
"ColorEarthyOrange":"大地橘",
"ColorEarthyRed":"大地紅",
"ColorEarthyYellow":"大地黃",
"ColorLightGray":"淺灰色",
"ColorMediumGray":"中灰色",
"ColorPastelBlue":"粉彩藍",
"ColorPastelGreen":"粉彩綠",
"ColorPastelOrange":"粉彩橘",
"ColorPastelPurple":"粉彩紫",
"ColorPastelRed":"粉彩紅",
"ColorPastelYellow":"粉彩黃",
"ColorPickerColor":"色彩",
"ColorPickerDefaultColor":"預設色彩(&amp;D)",
"ColorPickerMoreColors":"更多色彩(&amp;M)...",
"ColorProfessionalAqua":"專業青色",
"ColorProfessionalBlue":"專業藍",
"ColorProfessionalGreen":"專業綠",
"ColorProfessionalOrange":"專業橘",
"ColorProfessionalPurple":"專業紫",
"ColorProfessionalRed":"專業紅",
"ColorTempCooler":"較冷",
"ColorTempWarmer":"較暖",
"ColorVibrantBlue":"鮮豔藍",
"ColorVibrantGreen":"鮮豔綠",
"ColorVibrantOrange":"鮮豔橘",
"ColorVibrantPurple":"鮮豔紫",
"ColorVibrantRed":"鮮豔紅",
"ColorVibrantYellow":"鮮豔黃",
"ColorWhite":"白色",
"ColumnProperties":"欄屬性",
"Comma":"，",
"CommaSpace":"， ",
"Configuration":"設定",
"ConfigureProduct":"設定 {0}",
"ConfigWizardBasicInfo":"部落格首頁與登入",
"ConfigWizardChooseWeblogType":"選擇部落格類型",
"ConfigWizardComplete":"部落格設定完成",
"ConfigWizardDetectSettings":"正在偵測部落格設定",
"ConfigWizardLearnMore":"深入了解 {0}",
"ConfigWizardSelectImageEndpoint":"選取圖片集合",
"ConfigWizardSelectProvider":"選取部落格類型",
"ConfigWizardSelectWeblog":"選取部落格",
"ConfigWizardSharePointHomepage":"SharePoint 部落格首頁",
"ConfigWizardSharePointLogin":"SharePoint 部落格登入",
"ConfigWizardWelcome":"歡迎！",
"ConnectionRequired":"需要網際網路連線",
"CopyrightInformation":"著作權資訊",
"CropAspect16x9":"16x9",
"CropAspect35x5":"3.5x5",
"CropAspect4x3":"4x3",
"CropAspect4x6":"4x6",
"CropAspect5x7":"5x7",
"CropAspect85x11":"8.5x11",
"CropAspect8x10":"8x10",
"CropAspectCustom":"自訂",
"CropAspectOriginal":"原始",
"CropAspectRatioLabel":"比例(&amp;P)：",
"CropAspectSquare":"正方形",
"CropDialogTitle":"裁切",
"CropPane":"圖片裁切窗格",
"CropRemoveCrop":"移除裁切(&amp;R)",
"CropRotateFrame":"旋轉框架(&amp;F)",
"CropShowGridlines":"顯示格線(&amp;G)",
"Culture.UseItalics":"True",
"CustomizeMap":"自訂地圖",
"CWBasicCreateAccount":"如果您尚未擁有 {0} 帳號，請立即建立一個。按一下下方連結開啟網頁，開始線上註冊程序。",
"CWBasicHeader":"新增部落格帳號",
"CWBasicHomepage":"部落格網址(&amp;A)：",
"CWBasicHomepage2":"這是訪客用來閱讀您部落格的網址。",
"CWBasicText":"若要使用 {0}，您必須已擁有部落格服務的帳號。如果您尚未擁有現有部落格服務的帳號，請立即建立一個。",
"CWBasicTitle":"設定 {0} 以搭配 {1} 使用",
"CWBasicTitleDefaultService":"您的部落格",
"CWConfirmEditWeblogSettings":"編輯設定(&amp;E)...",
"CWConfirmFTPServer":"FTP 伺服器",
"CWConfirmSwitchToWeblog":"立即切換到此部落格(&amp;S)",
"CWConfirmText":"請確認您要儲存此部落格。",
"CWConfirmText2":"Writer 將定期檢查並下載您部落格的新設定資訊。",
"CWConfirmThanks":"您的部落格已設定完成",
"CWConfirmUploadSettings":"上傳圖片至：",
"CWConfirmWeblogName":"部落格名稱",
"CWGoogleBloggerDescription":"若要設定 Google Blogger，請登入。",
"CWGoogleBloggerSignInSuccess":"登入成功",
"CWGoogleBloggerTitle":"提供 Google Blogger 登入資訊",
"CWLiveIDCreateAccount":"如果您使用 Hotmail、Messenger 或 Xbox LIVE，您已擁有 Microsoft 帳號。",
"CWLiveIDCreateAccount2":"沒有 Microsoft 帳號嗎？",
"CWProgressHeader":"正在設定您的部落格帳號",
"CWSelectBlogText":"偵測到多個部落格。請從下方清單選取您要新增的部落格：",
"CWSelectImageEndpointText":"請選取您要上傳圖片的集合：",
"CWSelectProviderApiUrl":"伺服器 API 網址",
"CWSelectProviderApiUrlLabel":"部落格的遠端發佈網址(&amp;W)：",
"CWSelectProviderApiUrlLabel_ServiceDoc":"服務文件網址(&amp;W)：",
"CWSelectProviderText":"{0} 無法自動偵測您的部落格設定。請選取您所使用的部落格類型以繼續。",
"CWSelectProviderWeblogProvider":"部落格服務供應商",
"CWSelectProviderWeblogTypeLabel":"您所使用的部落格類型(&amp;T)：",
"CWSharePointHomepageUrl":"SharePoint 部落格網址(&amp;P)：",
"CWSharePointText":"若要使用 {0}，您必須擁有 SharePoint 部落格。",
"CWSharePointText2":"請輸入發佈到 SharePoint 部落格所需的登入資訊。",
"CWSharePointTitle":"設定 {0} 以搭配 SharePoint 部落格使用",
"CWSharePointTitle2":"提供 SharePoint 部落格登入資訊",
"CWSharePointUseSystemLogin":"使用我的 Windows 使用者名稱和密碼(&amp;W)",
"CWSpacesUsername":"Microsoft 帳號(&amp;M)：",
"CWSpacesUsernameExample":"(example555@hotmail.com)",
"CWStaticSiteCommandsBuildCommand":"建置命令：",
"CWStaticSiteCommandsBuildCommandSubtitle":"用於建置您的網站並將輸出儲存在本機的命令，以便準備發佈。若已啟用本機網站建置，則為必填。",
"CWStaticSiteCommandsPublishCommand":"發佈命令：",
"CWStaticSiteCommandsPublishCommandSubtitle":"用於將您的網站上傳至主機服務供應商的命令。如果已啟用本機網站建置，此命令通常會上傳建置命令的輸出。",
"CWStaticSiteCommandsSubtitle":"{0} 將執行您在下方指定的命令，並在發生錯誤時通知您。命令是使用系統命令解譯器執行，工作目錄為您的本機網站目錄。",
"CWStaticSiteCommandsTitle":"提供網站撰寫命令",
"CWStaticSiteConfigDetection":"{0} 已能夠自動判斷您網站的部分設定。請確認下一頁預先填入的詳細資料是否正確，並填寫其他遺漏的欄位。",
"CWStaticSiteFeaturesBuilding":"啟用本機網站建置",
"CWStaticSiteFeaturesDrafts":"啟用遠端草稿",
"CWStaticSiteFeaturesImages":"啟用圖片上傳",
"CWStaticSiteFeaturesPages":"啟用頁面",
"CWStaticSiteFeaturesSubtitle":"使用下方核取方塊定義您的靜態網站支援哪些功能。您可以在下列頁面中設定 Open Live Writer 的這些功能。",
"CWStaticSiteFeaturesTitle":"定義靜態網站功能",
"CWStaticSiteInitialSubtitle":"{0} 將嘗試根據您網站專案資料夾中的檔案自動偵測您的靜態網站設定。請選取您靜態網站的專案資料夾（例如 Git 存放庫）",
"CWStaticSiteInitialSubtitleAlreadyDetected":"{0} 已嘗試對您的網站執行設定偵測。如有需要，您可以在此變更網站路徑。您也可以從「設定」重新執行設定偵測。",
"CWStaticSiteInitialTitle":"提供靜態網站設定",
"CWStaticSiteLocalSiteFolderPicker":"請選取您靜態網站的專案資料夾（例如 Git 存放庫）",
"CWStaticSiteLocalSitePath":"本機靜態網站路徑：",
"CWStaticSitePathsDraftsPath":"草稿路徑：（相對路徑，若已啟用草稿則為必填）",
"CWStaticSitePathsImagesPath":"圖片路徑：（相對路徑，若已啟用圖片則為必填）",
"CWStaticSitePathsOutputPath":"建置輸出路徑：（相對路徑，若已啟用建置則為必填）",
"CWStaticSitePathsPagesInRoot":"頁面儲存在網站根目錄",
"CWStaticSitePathsPagesPath":"頁面路徑：（相對路徑，若已啟用頁面則為必填）",
"CWStaticSitePathsPostsPath":"文章路徑：（相對路徑）",
"CWStaticSitePathsSiteUrl":"公開網站 URL：",
"CWStaticSitePathsTitle":"提供網站 URL 和路徑",
"CWTitle":"新增部落格精靈",
"CWWelcomeAlreadyHave":"我已設定好部落格(&amp;A)",
"CWWelcomeCaption":"歡迎進入部落格的世界！",
"CWWelcomeClickNext":"按一下「下一步」以繼續。",
"CWWelcomeCreate":"建立新部落格(&amp;C)",
"CWWelcomeText":"使用 {0} 撰寫任何您感興趣的部落格。新增相片和影片，然後發佈到熱門部落格服務，包括 WordPress、Blogger 和 TypePad。",
"CWWelcomeWP":"WordPress(&amp;W)",
"Date":"日期",
"DecoratorBWDescription":"黑白",
"DecoratorBWLabel":"黑白",
"DecoratorCoolestTemperatureLabel":"最冷色調",
"DecoratorCoolTemperatureLabel":"冷色調",
"DecoratorDropShadow":"陰影",
"DecoratorEmbossDescription":"對選取的圖片套用浮雕效果。",
"DecoratorEmbossLabel":"浮雕",
"DecoratorGaussianBlurDescription":"對選取的圖片套用高斯模糊濾鏡。",
"DecoratorGaussianBlurLabel":"高斯模糊",
"DecoratorGroupOverlays":"疊加效果",
"DecoratorGroupTransformations":"變形",
"DecoratorInheritBorder":"繼承自部落格",
"DecoratorInstantPhoto":"即可拍相片",
"DecoratorNoBlurDescription":"移除選取圖片的模糊濾鏡。",
"DecoratorNoBlurLabel":"無模糊",
"DecoratorNoBorder":"無",
"DecoratorNoEmbossDescription":"移除選取圖片的浮雕效果。",
"DecoratorNoEmbossLabel":"無浮雕",
"DecoratorNoRecolorDescription":"移除套用於選取圖片的重新上色效果。",
"DecoratorNoRecolorLabel":"無重新上色",
"DecoratorNoSharpenDescription":"移除選取圖片的銳利化濾鏡。",
"DecoratorNoSharpenLabel":"無銳利化",
"DecoratorPhotopaper":"相紙",
"DecoratorReflection":"倒影",
"DecoratorRoundedCorners":"圓角",
"DecoratorSaturationDescription":"使選取圖片中的色彩更加鮮豔。",
"DecoratorSaturationLabel":"色彩強化",
"DecoratorSepiaDescription":"棕褐色調",
"DecoratorSepiaLabel":"棕褐色調",
"DecoratorSharpenDescription":"對選取的圖片套用銳利化濾鏡。",
"DecoratorSharpenLabel":"銳利化",
"DecoratorSolid1px":"實線，1 像素",
"DecoratorSolid3px":"實線，3 像素",
"DecoratorTemperatureDescription":"變更選取圖片中色彩的暖度。",
"DecoratorWarmestTemperatureLabel":"最暖色調",
"DecoratorWarmTemperatureLabel":"暖色調",
"DecoratorWatermark":"浮水印...",
"DefaultTemplateBodyFont":"Calibri, Trebuchet MS, Helvetica, Arial, Sans-Serif",
"DefaultTemplateTitleFont":"Calibri, Trebuchet MS, Helvetica, Arial, Sans-Serif",
"DeleteButton":"移除(&amp;M)...",
"DeleteSomething":"刪除 {0}",
"DictionaryLanguageLabel":"字典語言(&amp;L)：",
"DictionaryLanguageNone":"(無)",
"DimensionsFormat":"{0}x{1}",
"Disabled":"已停用",
"DontShowAgain":"不再顯示此訊息(&amp;D)",
"DownloadingWeblogStyle":"正在下載部落格佈景主題",
"DraftNameFormat":"草稿 {0}",
"Drafts":"草稿",
"DynamicCommandMenuInsert":"插入",
"DynamicCommandMenuMore":"更多(&amp;R)...",
"EditButton":"編輯(&amp;E)...",
"EditingName":"編輯",
"EditingRTLDefault":"預設 ({0})",
"EditingRTLExplanation":"變更部落格文章的閱讀方向。",
"EditingRTLName":"文字方向",
"EditingRTLNo":"由左至右",
"EditingRTLUse":"在編輯檢視中由右至左輸入文字(&amp;E)。",
"EditingRTLYes":"由右至左",
"EditingStyle":"部落格佈景主題",
"EditingText":"在線上變更佈景主題後",
"EditingUpdate":"更新佈景主題(&amp;U)",
"EditingUsing":"使用您的部落格佈景主題，在編輯時預覽文章發佈到線上後的外觀。",
"EditProxySettings":"設定 Proxy...",
"EmoticonAirplane":"飛機",
"EmoticonAlien":"外星人",
"EmoticonAngel":"天使",
"EmoticonAngrySmile":"憤怒的笑臉",
"EmoticonAnnoyed":"煩躁",
"EmoticonAuto":"汽車",
"EmoticonBaringTeethSmile":"齜牙笑臉",
"EmoticonBeRightBack":"馬上回來",
"EmoticonBirthdayCake":"生日蛋糕",
"EmoticonBlackSheep":"黑羊",
"EmoticonBowl":"碗",
"EmoticonBoy":"男孩",
"EmoticonBrokenHeart":"破碎的心",
"EmoticonBunny":"兔子",
"EmoticonCallMe":"打電話給我",
"EmoticonCamera":"相機",
"EmoticonCatFace":"貓臉",
"EmoticonClock":"時鐘",
"EmoticonCoffeeCup":"咖啡杯",
"EmoticonComputer":"電腦",
"EmoticonConfusedSmile":"困惑的笑臉",
"EmoticonCryingFace":"哭臉",
"EmoticonDevil":"惡魔",
"EmoticonDisappointedSmile":"失望的笑臉",
"EmoticonDogFace":"狗臉",
"EmoticonDontTellAnyoneSmile":"別告訴任何人的笑臉",
"EmoticonEmail":"電子郵件",
"EmoticonEmbarrassedSmile":"尷尬的笑臉",
"EmoticonEyeRollingSmile":"翻白眼的笑臉",
"EmoticonFilmstrip":"影片膠卷",
"EmoticonFingersCrossed":"手指交叉",
"EmoticonFlirtFemale":"調情女生",
"EmoticonFlirtMale":"調情男生",
"EmoticonFreezing":"結冰",
"EmoticonGhost":"幽靈",
"EmoticonGiftWithABow":"綁蝴蝶結的禮物",
"EmoticonGirl":"女孩",
"EmoticonGoat":"山羊",
"EmoticonGreenWithEnvy":"嫉妒",
"EmoticonHighFive":"擊掌",
"EmoticonHotSmile":"熱情笑臉",
"EmoticonIDontKnowSmile":"我不知道的笑臉",
"EmoticonInLove":"戀愛中",
"EmoticonIslandWithAPalmTree":"棕櫚樹島嶼",
"EmoticonJustKidding":"開玩笑的",
"EmoticonLaughingOutLoud":"哈哈大笑",
"EmoticonLeftHug":"左擁抱",
"EmoticonLightBulb":"燈泡",
"EmoticonLightning":"閃電",
"EmoticonMartiniGlass":"馬丁尼杯",
"EmoticonMobilePhone":"手機",
"EmoticonMoney":"金錢",
"EmoticonMug":"啤酒杯",
"EmoticonNerdSmile":"書呆子笑臉",
"EmoticonNinja":"忍者",
"EmoticonNote":"音符",
"EmoticonNyahNyah":"嘲笑",
"EmoticonOpenMouthedSmile":"張嘴笑臉",
"EmoticonPartySmile":"派對笑臉",
"EmoticonPeace":"和平",
"EmoticonPizza":"披薩",
"EmoticonPlate":"盤子",
"EmoticonPointingUp":"指向上方",
"EmoticonPrincess":"公主",
"EmoticonPunch":"出拳",
"EmoticonPunk":"龐克",
"EmoticonRainbow":"彩虹",
"EmoticonRedHeart":"紅心",
"EmoticonRedLips":"紅唇",
"EmoticonRedRose":"紅玫瑰",
"EmoticonRightHug":"右擁抱",
"EmoticonRollingOnTheFloorLaughing":"笑翻在地",
"EmoticonSadSmile":"悲傷的笑臉",
"EmoticonSarcasticSmile":"諷刺的笑臉",
"EmoticonSchool":"學校",
"EmoticonSchoolBus":"校車",
"EmoticonSecretTellingSmile":"悄悄話笑臉",
"EmoticonSendAKiss":"送飛吻",
"EmoticonsGalleryPopular":"全部",
"EmoticonsGalleryRecent":"最近使用",
"EmoticonShifty":"鬼鬼祟祟",
"EmoticonSickSmile":"生病的笑臉",
"EmoticonSleepingHalfMoon":"睡眠半月",
"EmoticonSleepySmile":"睏倦的笑臉",
"EmoticonSmile":"微笑",
"EmoticonSmileWithTongueOut":"吐舌笑臉",
"EmoticonSnail":"蝸牛",
"EmoticonSoccerBall":"足球",
"EmoticonStar":"星星",
"EmoticonSteamingMad":"冒煙的憤怒",
"EmoticonsTooltipOneAutoReplace":"{0}  {1}",
"EmoticonsTooltipTwoAutoReplace":"{0}  {1} 或 {2}",
"EmoticonStormCloud":"烏雲",
"EmoticonSun":"太陽",
"EmoticonSurprisedSmile":"驚訝的笑臉",
"EmoticonTelephoneReceiver":"電話聽筒",
"EmoticonThinkingSmile":"思考的笑臉",
"EmoticonThumbsDown":"拇指朝下",
"EmoticonThumbsUp":"拇指朝上",
"EmoticonTurtle":"烏龜",
"EmoticonUmbrella":"雨傘",
"EmoticonVampireBat":"吸血鬼蝙蝠",
"EmoticonWhoMe":"是我嗎？",
"EmoticonWiltedRose":"枯萎的玫瑰",
"EmoticonWinkingSmile":"眨眼笑臉",
"EmoticonWork":"工作",
"Enabled":"已啟用",
"ErrorOccurredDeletingDraft":"刪除草稿時發生錯誤",
"ErrorOccurredDeletingDraftDetails":"嘗試刪除草稿時發生未預期的錯誤：{0}",
"FileUploadFailedCaption":"下列圖片無法發佈，因為部落格不支援圖片發佈。",
"FileUploadFailedException":"無法發佈檔案",
"FileUploadFailedFTP":"Open Live Writer 可設定為將圖片發佈到 FTP 帳號。",
"FileUploadFailedFTP2":"您要立即設定 FTP 帳號以便發佈圖片嗎？",
"FileUploadFailedTitle":"部落格不支援圖片上傳",
"FileUploadFTPServer":"FTP 伺服器",
"FileUploadNone":"不上傳",
"FileUploadUploadToWeblog":"部落格",
"FindCategory":"尋找類別",
"FindDirection":"方向",
"FindDirectionDown":"向下(&amp;D)",
"FindDirectionUp":"向上(&amp;U)",
"FindNextButton":"尋找下一個(&amp;F)",
"FindTitle":"尋找",
"FindWhatLabel":"尋找(&amp;N)：",
"ForgotMyPassword":"忘記密碼",
"FtpFolderPath":"發佈資料夾路徑(&amp;P)：",
"FtpFolderUrl":"發佈資料夾的網址(&amp;W)：",
"FtpHelp":"如何設定 FTP 網站？",
"FtpHostname":"主機名稱(&amp;H)：",
"FtpLoginDomain":"FTP",
"FtpPassword":"密碼(&amp;P)：",
"FtpText":"FTP 設定",
"FtpUsername":"使用者名稱(&amp;U)：",
"FuturePostWarningDialogTitle":"Open Live Writer",
"FuturePostWarningDontShowAgain":"一律立即發佈，不再詢問(&amp;A)",
"FuturePostWarningExplanation":"此部落格服務無法延遲發佈至您設定的日期。您要立即發佈嗎？",
"FuturePostWarningTitle":"無法設定未來的發佈日期",
"GDataCaptchaAlternate":"視障使用者可在此存取測試的音訊版本。",
"GDataCaptchaPrompt":"請輸入下方圖片中顯示的字元。",
"GDataCaptchaTitle":"解鎖 Google 帳號",
"GenericLoginError":"無法登入 Live ID。",
"GigabytesFormat":"{0}GB",
"GlossaryAutomaticallyLink":"自動連結相符的詞語(&amp;U)",
"GlossaryAutomaticallyLinkFirstTime":"每篇文章中每個詞語只連結一次(&amp;N)",
"GlossaryAutomaticLinkOptions":"自動連結選項",
"GlossaryExampleTitle":"Open Live Writer 網站",
"GlossaryPrefName":"自動連結",
"GlossarySelectLink":"選取連結",
"GlossaryTextCol":"詞語",
"GlossaryUrlCol":"網址",
"Heading1":"標題 1",
"Heading2":"標題 2",
"Heading3":"標題 3",
"Heading4":"標題 4",
"Heading5":"標題 5",
"Heading6":"標題 6",
"Height":"高度",
"HeightColon":"高度(&amp;H)：",
"HeightLabel":"高度(&amp;H)：",
"HelpButton":"說明(&amp;H)",
"HideProperties":"隱藏屬性",
"HomepageUrl":"網站位址：",
"ImageEffectsColorModesCategory":"色彩模式",
"ImageEffectsColorTemperatureCategory":"色彩溫度",
"ImageEffectsEmbossCategory":"浮雕",
"ImageEffectsGaussianCategory":"高斯模糊",
"ImageEffectsNoBlurCategory":"無模糊",
"ImageEffectsNoEmbossCategory":"無浮雕",
"ImageEffectsNoRecolorCategory":"無重新上色",
"ImageEffectsNoSharpenCategory":"無銳利化",
"ImageEffectsSharpenCategory":"銳利化",
"ImagesBlogOpt":"部落格服務(&amp;B)",
"ImagesFilterString":"所有圖片 (*.gif, *.jpg, *.jpeg, *.png)",
"ImagesFtpConfig":"變更 FTP 設定(&amp;C)...",
"ImagesFtpOpt":"FTP 站台(&amp;F)：",
"ImagesPanel":"圖片",
"ImagesText":"當您在部落格文章中新增圖片時，要將圖片上傳到此部落格服務還是 FTP 站台？",
"ImagesUpload":"上傳",
"ImageViewerDisplayFormatGroup":"使用 {0} [{1}]",
"ImageViewerDisplayFormatSingle":"使用 {0}",
"ImageViewerGroupLabel":"群組（選用）(&amp;G)：",
"ImageViewerLabel":"啟用 {0}(&amp;E)",
"ImgAltTextAlternateText":"替代文字(&amp;A)：",
"ImgAltTextPicture":"圖片：",
"ImgAltTextTitle":"標題(&amp;T)：",
"ImgSBActions":"動作",
"ImgSBAdvanced":"進階",
"ImgSBAlignCenter":"置中",
"ImgSBAlignInline":"行內",
"ImgSBAlignLeft":"靠左",
"ImgSBAlignRight":"靠右",
"ImgSBAppliedEffects":"已套用的效果：",
"ImgSBBorders":"框線",
"ImgSBBrightness":"對比...",
"ImgSBCrop":"裁切...",
"ImgSBCustomize":"自訂預設圖片大小",
"ImgSBDefaultImageSizes":"預設圖片大小",
"ImgSBEffect":"效果",
"ImgSBEffects":"效果",
"ImgSBEffectsLabel":"效果：",
"ImgSBHeader":"圖片",
"ImgSBImageEffects":"效果",
"ImgSBImageSize":"大小",
"ImgSBImageSizeLabel":"大小(&amp;S)：",
"ImgSBLargeImage":"大：",
"ImgSBLayout":"版面配置",
"ImgSBLinkOptions":"原始圖片選項",
"ImgSBLinkOptionsDisabledTooltip":"此命令對網路圖片及某些圖片類型已停用。",
"ImgSBLinkTo":"連結到",
"ImgSBLocalImage":"本機：{0}",
"ImgSBLocalImage2":"本機：{0}/{1}",
"ImgSBLockRatio":"鎖定比例(&amp;R)",
"ImgSBMarginBottom":"下方：",
"ImgSBMarginCustomMargins":"自訂",
"ImgSBMarginLeft":"左方：",
"ImgSBMarginNoMargins":"無",
"ImgSBMarginRight":"右方：",
"ImgSBMargins":"邊距：",
"ImgSBMarginTop":"上方：",
"ImgSBMaximumHeightLabel1":"最大高度(&amp;H)：",
"ImgSBMaximumHeightLabel2":"最大高度(&amp;E)：",
"ImgSBMaximumHeightLabel3":"最大高度(&amp;T)：",
"ImgSBMaximumWidthLabel1":"最大寬度(&amp;W)：",
"ImgSBMaximumWidthLabel2":"最大寬度(&amp;I)：",
"ImgSBMaximumWidthLabel3":"最大寬度(&amp;D)：",
"ImgSBMediumImage":"中：",
"ImgSBOpenInNewWindow":"在新視窗中開啟(&amp;O)",
"ImgSBOther":"其他",
"ImgSBRevert":"還原為預設設定",
"ImgSBRotate":"旋轉",
"ImgSBSave":"儲存設定為預設值",
"ImgSBSizerCustom":"自訂",
"ImgSBSizerLarge":"大",
"ImgSBSizerMedium":"中",
"ImgSBSizerOriginal":"原始",
"ImgSBSizerSmall":"小",
"ImgSBSizerUnknown":"(自訂)",
"ImgSBSmallImage":"小：",
"ImgSBTextWrapping":"文字換行：",
"ImgSBTilt":"傾斜...",
"Insert":"插入",
"InsertButton":"插入(&amp;I)",
"InsertButtonText":"插入",
"InsertImageButton":"插入(&amp;S)",
"InsertImageDimensionsFormat":"{0}x{1}",
"InsertImageDimensionsFormatScaled":"{0}（已調整大小以在此視窗中預覽）",
"InsertImageFileName":"檔案名稱：",
"InsertImageImageUrl":"圖片網址(&amp;W)：",
"InsertImageInsertFromFile":"從檔案",
"InsertImageInsertFromWeb":"從網路",
"InsertImageLinkTo":"連結到(&amp;L)：",
"InsertImageOpenInNewWindow":"在新視窗中開啟(&amp;O)",
"InsertImagePreviewButton":"預覽(&amp;P)",
"InsertImageSize":"大小：",
"InsertLink":"插入超連結",
"InsertLinkDotDotDot":"超連結...",
"InsertLinkTooltip":"在目前的文件中插入超連結",
"InsertMap":"插入地圖",
"InsertPicture":"插入圖片",
"InsertPictureDotDotDot":"圖片...",
"InsertPictureTooltip":"在目前的文件中插入圖片",
"InsertTable":"插入表格",
"InsertTableDotDotDot":"表格...",
"InsertTableTooltip":"在目前的文件中插入表格",
"KilobytesFormat":"{0}KB",
"LCPrefCaption":"將支援 Live Clipboard 格式的網路內容貼上到 {0}。",
"LCPrefChangeButton":"變更...",
"LCPrefContentType":"內容類型：",
"LCPrefDescription":"描述",
"LCPrefDetails":"詳細資料",
"LCPrefDetailsGroupBoxFormat":"「{0}」格式的詳細資料",
"LCPrefFormat":"格式",
"LCPrefHandledBy":"處理方式：",
"LCPrefMoreAboutLiveClipboard":"深入了解 Live Clipboard...（英文）",
"LCPrefNoFormatSelected":"(未選取格式)",
"LCPrefOptionsButton":"選項...",
"LCPrefPanelName":"Live Clipboard",
"LCPrefSupportedFormats":"支援的格式(&amp;S)：",
"LinkAddToGlossary":"自動連結到此文字(&amp;M)",
"LinkAdvanced":"進階 {0}(&amp;A)",
"LinkEditHyperlink":"編輯超連結",
"LinkFormTitle":"插入超連結",
"LinkGlossaryEdit":"編輯自動連結",
"LinkGlossaryRelOptional":"Rel（選用）(&amp;R)：",
"LinkGlossaryText":"文字(&amp;X)：",
"LinkGlossaryTitle":"新增自動連結",
"LinkGlossaryTitleOptional":"標題（選用）(&amp;T)：",
"LinkGlossaryUrl":"網址(&amp;W)：",
"LinkLinkTo":"連結到(&amp;L)",
"LinkNewWindowLabel":"在新視窗中開啟連結(&amp;O)",
"LinkOptionsTooltip":"瀏覽連結",
"LinkRelLabel":"Rel(&amp;E)：",
"LinkRemoveLink":"移除超連結(&amp;R)",
"LinkSelectionContainsImage":"[選取範圍包含圖片]",
"LinkTextLabel":"要顯示的文字(&amp;X)：",
"LinkTitleLabel":"標題(&amp;T)：",
"LinkTo":"連結到(&amp;L)",
"LinkToNone":"無",
"LinkToNoneDescription":"使圖片不成為連結。",
"LinkToNoneLabelTitle":"連結到：無",
"LinkToolTip":"CTRL + 按一下以開啟連結：{0}",
"LinkToPost":"連結到文章",
"LinkToSource":"原始圖片",
"LinkToSourceDescription":"按一下選取的圖片時，瀏覽到原始圖片。",
"LinkToSourceLabelTitle":"連結到：原始圖片",
"LinkToURL":"網址",
"LinkToURLDescription":"選擇按一下選取的圖片時要前往的位置。",
"LinkToURLLabelTitle":"連結到：網址",
"LinkToWebPageURL":"連結到網址：",
"LiveIDPrivacy":"隱私權原則",
"Login":"登入",
"ManageWeblog":"管理部落格",
"Map":"地圖",
"MapAerial":"空拍",
"MapAlignCenter":"置中",
"MapAlignInline":"行內",
"MapAlignLeft":"靠左",
"MapAlignRight":"靠右",
"MapBirdseye":"鳥瞰",
"MapBirdseyeButton":"切換鳥瞰檢視",
}

# Part 2 (entries 695-1388): plain text values; xml_escape() will encode & -> &amp;
PART2 = {
"MapBirdseyeLabel":"&鳥瞰圖",
"MapCustomMargins":"自訂邊界",
"MapDirectionEast":"東",
"MapDirectionNorth":"北",
"MapDirectionSouth":"南",
"MapDirectionWest":"西",
"MapFindAddress":"&尋找地點：",
"MapImageAltText":"地圖圖片",
"MapNoMargins":"無邊界",
"MapPushpinTip":"提示：在地圖上按一下右鍵以新增圖釘",
"MapRoad":"道路",
"MapSBBottom":"下方",
"MapSBCaption":"說明文字：",
"MapSBCustomize":"自訂地圖...",
"MapSBCustomizeTooltip":"編輯地圖位置、樣式與圖釘",
"MapSBLayoutHeader":"版面配置",
"MapSBLeft":"左側",
"MapSBMapHeader":"地圖",
"MapSBMargins":"邊界：",
"MapSBRight":"右側",
"MapSBTop":"上方",
"MapSBViewMap":"在 Live.com 上檢視地圖",
"MapSBWrapping":"文繞圖：",
"MapSearch":"搜尋",
"MapSeeInBirdseye":"查看此地點的鳥瞰視圖",
"MapShowLabel":"顯示(&W)標籤",
"MapStyle":"地圖樣式",
"MapZoomIn":"放大",
"MapZoomOut":"縮小",
"MapZoomSlider":"縮放滑桿",
"MarkupTypeHTML":"HTML",
"MarkupTypeXHTML":"XHTML",
"MaximizeButtonTooltip":"最大化",
"MaxLgHeight":"最大大型高度",
"MaxLgWidth":"最大大型寬度",
"MaxMdHeight":"最大中型高度",
"MaxMdWidth":"最大中型寬度",
"MaxSmHeight":"最大小型高度",
"MaxSmWidth":"最大小型寬度",
"MegabytesFormat":"{0}MB",
"MethodNotImplemented":"方法未實作",
"MethodNotImplementedDetail":"已安裝的外掛程式實作不正確，導致發生錯誤。您或許可以聯絡以下外掛程式的發行者來解決此問題。或者，您可以解除安裝以下所提及的外掛程式，以避免日後再次發生此錯誤。\n名稱：{0}\n\n發行者：{1}\n\n未實作的方法：{2}",
"MinimizeButtonTooltip":"最小化",
"MissingPostLinkCaption":"{0} 沒有可用的連結",
"MissingPostLinkExplanation":"所選的 {0} 沒有可用的連結。這可能是因為您的部落格服務未向 {1} 提供 {0} 的連結。您可以嘗試透過「部落格設定」對話方塊的「帳號」面板重新偵測您的部落格帳號設定，以解決此問題。",
"MissingPostLinkTitle":"沒有可用的連結",
"MoreDotDotDot":"更多...",
"MoreDrafts":"更多草稿",
"MoreDraftsTooltip":"開啟上方未列出的其他草稿",
"MorePosts":"更多最近文章",
"MorePostsTooltip":"開啟上方未列出的其他文章",
"MoreWeblogs":"更多部落格(&O)...",
"MoveDown":"向下移動(&D)",
"MoveUp":"向上移動(&U)",
"MyFavorites":"我的最愛",
"MyVideos":"我的影片",
"Name":"部落格",
"NewFolder":"新增資料夾",
"NewFolderPrompt":"新資料夾名稱：",
"NewFolderTitle":"建立新資料夾",
"NewFolderTooltip":"建立新資料夾",
"No":"否",
"NoButton":"否(&N)",
"NotConnected":"您必須連線至網際網路才能插入及編輯地圖。",
"NoThings":"(無 {0})",
"OKButtonText":"確定",
"Open":"開啟",
"OpenPostDelete":"刪除(&D)",
"OpenPostItems":"個項目",
"OpenPostNoDraftsAvailable":"沒有可用的草稿。",
"OpenPostNoPagesAvailable":"沒有可用的頁面。",
"OpenPostNoPostsAvailable":"沒有可用的文章。",
"OpenPostOpenFrom":"開啟來源(&O)：",
"OpenPostPages":"頁面(&A)",
"OpenPostPosts":"文章(&P)",
"OpenPostRefresh":"重新整理(&R)",
"OpenPostRefreshTooltip":"重新整理文章",
"OpenPostRefreshTooltipPages":"重新整理頁面",
"OpenPostShow":"顯示(&S)：",
"Options":"選項",
"OptionsButton":"選項...",
"Page":"頁面",
"PageLower":"頁面",
"PageProperties":"頁面屬性",
"Pages":"頁面(&A)",
"PagesLower":"頁面",
"PanelNameAccounts":"帳號",
"Paragraph":"段落",
"Paragraphs":"段落",
"PassportLoginNoUserPass":"請輸入 Microsoft 帳號與密碼以繼續。",
"PassportLoginNoUserPassTitle":"需要 Microsoft 帳號與密碼",
"PassportLoginSignIn":"登入",
"PassportLoginTitle":"登入 Microsoft 帳號",
"Password":"密碼：",
"PasswordChar":"0x25CF",
"PasswordLabel":"密碼(&P)：",
"PasteSpecial":"選擇性貼上",
"PasteSpecialHtmlDesc":"保留所有格式設定，包括可能無法在您的部落格中正確顯示的格式。基於安全考量，指令碼將會被移除。",
"PasteSpecialHtmlLabel":"保留格式設定(&K)",
"PasteSpecialPlaintextDesc":"移除所有格式設定 (換行符號除外)。保留連結與圖片。適用於僅複製內容。",
"PasteSpecialPlaintextLabel":"移除格式設定(&R)",
"PasteSpecialTextFormatted":"HTML(&H)",
"PasteSpecialTextFormattedDesc":"將文字解譯為 HTML 原始碼。複製的內容將以格式化方式顯示。適用於圖片、內嵌物件等。",
"PasteSpecialTextPlainText":"純文字(&P)",
"PasteSpecialTextPlainTextDesc":"標準純文字貼上。所有 HTML 標籤將會被跳脫處理。",
"PasteSpecialThinnedDesc":"移除額外的格式設定，例如 MS Office 特有的格式、CSS 樣式及表格。保留相對標題大小、基本格式設定，並配合您的部落格佈景主題進行對齊。",
"PasteSpecialThinnedLabel":"精簡 HTML(&T)",
"Percent":"百分比",
"PhotoPreview":"內嵌相片預覽器",
"PingPrefName":"Ping 伺服器",
"PingPrefUrl":"Ping 下列網址（每行一個網址）(&P)",
"Pixels":"像素",
"Plugin_Map_InsertableContentSource_MenuText":"地圖(&M)",
"Plugin_Map_InsertableContentSource_SidebarText":"地圖",
"Plugin_Map_WriterPlugin_Description":"在您的部落格文章中嵌入 Live 搜尋地圖。",
"Plugin_Map_WriterPlugin_Name":"Live 搜尋地圖",
"Plugin_Tags_InsertableContentSource_MenuText":"標籤(&S)",
"Plugin_Tags_InsertableContentSource_SidebarText":"標籤",
"Plugin_Tags_WriterPlugin_Description":"使用熱門標籤網站或自訂 HTML 為您的文章新增標籤。",
"Plugin_Tags_WriterPlugin_Name":"標籤",
"Plugin_Video_Alignment_Inline":"內嵌",
"Plugin_Video_Alignment_Left":"左對齊",
"Plugin_Video_Alignment_Right":"右對齊",
"Plugin_Video_Alt_Text":"影片",
"Plugin_Video_Cannot_Parse_Url":"無法解析影片網址",
"Plugin_Video_Cannot_Parse_Url_Message":"未知的提供者或不完整的網址。",
"Plugin_Video_Caption_Size":".8em",
"Plugin_Video_Copyright_Notice":"請尊重著作權",
"Plugin_Video_Editor_Cancel":"取消發佈",
"Plugin_Video_Editor_Caption":"說明文字：",
"Plugin_Video_Editor_Layout_Header":"版面配置",
"Plugin_Video_Editor_Link_Text":"觀看此影片",
"Plugin_Video_Editor_Margin_Bottom":"下方",
"Plugin_Video_Editor_Margin_Left":"左側",
"Plugin_Video_Editor_Margin_Right":"右側",
"Plugin_Video_Editor_Margin_Top":"上方",
"Plugin_Video_Editor_Margins":"邊界：",
"Plugin_Video_Editor_Player_Style":"播放器樣式：",
"Plugin_Video_Editor_Text_Wrap":"文繞圖：",
"Plugin_Video_Editor_Title":"{0} 影片",
"Plugin_Video_Error_Unexpected_Title":"未預期的例外狀況",
"Plugin_Video_Margins_Custom":"自訂邊界",
"Plugin_Video_Margins_None":"無邊界",
"Plugin_Video_Player_Automatic":"自動",
"Plugin_Video_Player_Embed":"內嵌於頁面",
"Plugin_Video_Player_Preview":"預覽加連結",
"Plugin_Video_Provider_Select":"選取影片提供者",
"Plugin_Video_Publish_Categories_Animals":"動物",
"Plugin_Video_Publish_Categories_Animation":"動畫",
"Plugin_Video_Publish_Categories_Autos":"汽車",
"Plugin_Video_Publish_Categories_Blogs":"部落格",
"Plugin_Video_Publish_Categories_Comedy":"喜劇",
"Plugin_Video_Publish_Categories_Commercials":"廣告",
"Plugin_Video_Publish_Categories_Education":"教育",
"Plugin_Video_Publish_Categories_Entertainment":"娛樂",
"Plugin_Video_Publish_Categories_Film":"電影",
"Plugin_Video_Publish_Categories_Games":"遊戲",
"Plugin_Video_Publish_Categories_How_To":"教學與風格",
"Plugin_Video_Publish_Categories_Movies":"電影",
"Plugin_Video_Publish_Categories_Music":"音樂",
"Plugin_Video_Publish_Categories_News":"新聞與政治",
"Plugin_Video_Publish_Categories_Non_Profit":"非營利與社會運動",
"Plugin_Video_Publish_Categories_People":"人物",
"Plugin_Video_Publish_Categories_Politics":"政治",
"Plugin_Video_Publish_Categories_Screencast":"螢幕錄製",
"Plugin_Video_Publish_Categories_Sports":"運動",
"Plugin_Video_Publish_Categories_Technology":"科技",
"Plugin_Video_Publish_Categories_Travel":"旅遊",
"Plugin_Video_Publish_Filename_Seperator":"_",
"Plugin_Video_Publish_Message":"等待影片完成發佈",
"Plugin_Video_Publish_Safety_View":"查看安全提示",
"Plugin_Video_Publish_Terms_View":"查看使用條款",
"Plugin_Video_Snapshot_Error_Message":"嘗試產生影片快照時發生以下錯誤：{0}",
"Plugin_Video_Snapshot_Error_Title":"擷取影片快照時發生錯誤",
"Plugin_Video_Soapbox_LoggingIn":"登入中...",
"Plugin_Video_Soapbox_None_Found":"找不到影片。",
"Plugin_Video_Soapbox_Not_Logged_In":"尚未登入",
"Plugin_Video_Soapbox_Passport_Login":"登入(&S)",
"Plugin_Video_Soapbox_Passport_Password":"密碼(&P)：",
"Plugin_Video_Soapbox_Passport_Username":"Microsoft 帳號 ID(&M)：",
"Plugin_Video_Soapbox_Publish_Categories":"類別(&C)：",
"Plugin_Video_Soapbox_Publish_Description":"描述(&D)：",
"Plugin_Video_Soapbox_Publish_Login":"登入",
"Plugin_Video_Soapbox_Publish_Permissions":"權限(&E)：",
"Plugin_Video_Soapbox_Publish_Permissions_Hidden":"隱藏",
"Plugin_Video_Soapbox_Publish_Permissions_Public":"公開",
"Plugin_Video_Soapbox_Publish_Tab_Title":"從檔案",
"Plugin_Video_Soapbox_Publish_Tags":"標籤(&G)：",
"Plugin_Video_Soapbox_Publish_Title":"標題(&T)：",
"Plugin_Video_Soapbox_Publish_Video_File":"影片檔案(&F)：",
"Plugin_Video_Soapbox_Publish_Video_File_Open":"...",
"Plugin_Video_Soapbox_Publish_Video_Open_File":"開啟影片檔案",
"Plugin_Video_Soapbox_Result_Range":"影片 {0} 至 {1}",
"Plugin_Video_Soapbox_Result_Single":"影片 {0}",
"Plugin_Video_Soapbox_Retrieve_Msg":"正在擷取影片清單...",
"Plugin_Video_Soapbox_Soap_Error":"Soapbox 服務傳回錯誤。",
"Plugin_Video_Soapbox_Switch_User":"切換使用者",
"Plugin_Video_Soapbox_Thumbnail_Downloading":"正在下載預覽...",
"Plugin_Video_Soapbox_Thumbnail_None":"無可用預覽",
"Plugin_Video_Soapbox_Total_Videos":"(共 {0} 個)",
"Plugin_Video_Soapbox_Web_Error":"搜尋要求逾時。",
"Plugin_Video_Unknown_Provider":"未知的提供者",
"Plugin_Video_Video_Header":"影片",
"Plugin_Video_Web_Video_Download_Error":"由於影片服務使用量過高，無法從服務存取所選影片。請再試一次。",
"Plugin_Video_Web_Video_Download_Error_Title":"影片存取錯誤",
"Plugin_Video_Web_Video_Enter_Prompt":"影片網址或內嵌碼(&W)：",
"Plugin_Video_Web_Video_Preview_Button":"預覽(&V)",
"Plugin_Video_Web_Video_Provider":"提供者：{0}",
"Plugin_Video_Web_Video_Service_Blank":"提供者：",
"Plugin_Video_Web_Video_Size":"大小：{0} x {1}",
"Plugin_Video_Web_Video_Size_Blank":"大小：",
"Plugin_Video_Web_Video_Tab_Name":"從網路",
"Plugin_Video_XML_Error_Embed_Format":"缺少 Embed Format 參數",
"Plugin_Video_XML_Error_Embed_Pattern":"缺少 Embed Pattern 參數",
"Plugin_Video_XML_Error_Service_Id":"缺少 Service Id 參數",
"Plugin_Video_XML_Error_Service_Name":"缺少 Service Name 參數",
"Plugin_Video_XML_Error_Size":"缺少 Size 參數",
"Plugin_Video_XML_Error_Url_Format":"缺少 Web Address Format 參數",
"Plugin_Video_XML_Error_Url_Pattern":"缺少 Web Address Pattern 參數",
"Plugin_Video_Youtube_Publish_Name":"YouTube",
"Plugin_Video_YouTube_Publish_Terms_Agree":"是，我同意 YouTube 使用條款，且我擁有此影片的所有著作權，或已獲得上傳的授權。請勿在未獲許可的情況下上傳電視節目、音樂錄影帶、音樂演唱會或廣告，除非這些內容完全由您自己創作。",
"Plugin_Video_YouTube_Publish_Video_File_Open_Filter_Ext":"All Video Files (*.avi;*.wmv;*.mpg;*.mpeg;*.mp4;*.mpeg4;*.mov;*)|*.avi;*.wmv;*.mpg;*.mpeg;*.mp4;*.mpeg4,*.mov;|All Files (*.*)|*.*",
"Plugin_Videos_InsertableContentSource_MenuText":"影片(&V)",
"Plugin_Videos_InsertableContentSource_SidebarText":"影片",
"Plugin_Videos_Load_Error_Message":"由於影片服務負載過高，無法載入影片以插入編輯器。",
"Plugin_Videos_Load_Error_Title":"無法載入影片",
"Plugin_Videos_Select_Video_Form":"插入影片",
"Plugin_Videos_Video_Size":"影片大小：{0} x {1}",
"Plugin_Videos_WriterPlugin_Description":"使用熱門影片提供者在您的文章中新增影片。",
"Plugin_Videos_WriterPlugin_Name":"影片",
"Plugin_WebImage_Title":"插入網路圖片",
"Plugin_WebImage_WriterPlugin_Description":"從網路新增圖片至您的文章。",
"PluginInsertSidebarText":"{0}...",
"PluginInsertSidebarTooltip":"將 {0} 插入目前文件",
"PluginPrefCaption":"開啟或關閉外掛程式，以延伸 {0} 的使用方式。",
"PluginPrefDetails":"外掛程式詳細資料",
"PluginPrefDisable":"關閉(&F)",
"PluginPrefEnable":"開啟(&N)",
"PluginPrefInstalled":"目前已安裝的外掛程式(&P)：",
"PluginPrefLink":"線上取得外掛程式...",
"PluginPrefName":"外掛程式",
"PluginPrefNameCol":"外掛程式",
"PluginPrefNone":"(未選取外掛程式)",
"PluginPrefStatCol":"狀態",
"PluginPrefTooltip":"按一下這裡以深入了解此外掛程式。",
"PluginPublishProgress":"正在執行外掛程式：{0}",
"PluginSidebarDisabled":"所選項目的外掛程式已停用。",
"PluginSidebarNotEditable":"所選項目無法編輯。",
"Post":"文章",
"PostCountAccessible":"文章數量",
"PostEditorBodyRegion":"文章內文",
"PostEditorDiskSpaceExceptionMessage":"磁碟空間不足。",
"PostEditorPrefAuto":"定期儲存自動回復資訊(&U)",
"PostEditorPrefBrowseFolder":"瀏覽",
"PostEditorPrefClose":"發佈後關閉視窗(&W)",
"PostEditorPrefEditing":"編輯",
"PostEditorPrefGeneral":"一般選項",
"PostEditorPrefName":"偏好設定",
"PostEditorPrefNew":"每篇文章開啟新視窗(&E)",
"PostEditorPrefPostLocation":"本機草稿與最近文章資料夾",
"PostEditorPrefPostWindows":"文章視窗",
"PostEditorPrefPublishing":"發佈",
"PostEditorPrefRemind":"發佈前提醒我新增標籤(&T)",
"PostEditorPrefRemindCat":"發佈前提醒我新增類別(&C)",
"PostEditorPrefSide":"插入可編輯項目時顯示工作窗格(&H)",
"PostEditorPrefSingle":"使用單一視窗編輯所有文章(&S)",
"PostEditorPrefTitle":"發佈前提醒我輸入標題(&R)",
"PostEditorPrefUnsave":"僅在目前文章有未儲存的變更時才開啟新視窗(&O)",
"PostEditorPrefView":"發佈後檢視部落格(&V)",
"PostEditorStorageExceptionMessage":"存取本機文章時發生未預期的錯誤 ({0})\n\n{1}",
"PostEditorStorageExceptionMessage2":"存取本機文章時發生未預期的磁碟存取錯誤 ({0})\n\n{1}",
"PostEditorStorageExceptionTitle":"存取本機文章時發生錯誤",
"PostEditorStorageExceptionTitle2":"存取本機文章時發生錯誤",
"PostEditorTitleRegion":"文章標題",
"PostLinkTooltipFormat":"{0}\n{1} ({2})",
"PostLinkTooltipFormatNoBlogTitle":"{0}\n({1})",
"PostLower":"文章",
"PostPageFilter":"篩選 {0}",
"PostProperties":"文章屬性",
"PostPublishFileUploadErrorCaption1":"{0} 已成功發佈，但上傳支援檔案時發生錯誤：",
"PostPublishFileUploadErrorCaption2":"視錯誤性質而定，您或許可以重試來成功上傳支援檔案。或者，您可以考慮從部落格刪除此 {0}。",
"PostPublishFileUploadErrorTitle":"上傳支援檔案時發生錯誤",
"Posts":"文章(&P)",
"PostsLower":"文章",
"PPCRL_AUTHSTATE_E_EXPIRED":"驗證已過期。",
"PPCRL_E_AUTH_SERVICE_UNAVAILABLE":"無法連線至驗證服務。",
"PPCRL_REQUEST_E_BAD_MEMBER_NAME_OR_PASSWORD":"無法辨識使用者名稱或密碼。",
"PPCRL_REQUEST_E_CANCELLED":"要求已取消。",
"PPCRL_REQUEST_E_CLIENT_DEPRECATED":"發出此要求的用戶端已不再受登入伺服器支援。請升級至較新的版本。",
"PPCRL_REQUEST_E_FORCE_SIGNIN":"驗證權杖已過期。",
"PPCRL_REQUEST_E_INVALID_MEMBER_NAME":"無法辨識使用者名稱。",
"PPCRL_REQUEST_E_PASSWORD_LOCKED_OUT":"使用者帳號已被封鎖。",
"PrivacyPreferencesCodeOfConduct":".NET Foundation 貢獻者行為準則",
"PrivacyPreferencesPanelName":"信任中心",
"PrivacyPreferencesPrivacyExplanation":"您的隱私權非常重要。如需深入了解 Open Live Writer 如何協助保護您的隱私，請參閱：",
"PrivacyPreferencesPrivacyStatement":".NET Foundation 隱私權原則",
"ProductDisplayVersion":"組建 {0}",
"ProductNameVersioned":"Open Live Writer",
"ProgressAnalyzingHomepage":"正在分析部落格首頁網址與內容...",
"ProgressAnalyzingInterface":"正在分析部落格發佈介面...",
"ProgressAnalyzingWeblogList":"正在分析部落格清單...",
"ProgressCompletedSettingsDetection":"已完成設定偵測",
"ProgressCreatingEditingTemplate":"正在建立編輯範本...",
"ProgressDetectingWeblogCategories":"正在偵測部落格類別...",
"ProgressDetectingWeblogCharSet":"正在偵測部落格字元集...",
"ProgressDetectingWeblogEditingStyle":"正在偵測部落格編輯佈景主題...",
"ProgressDetectingWeblogIcon":"正在偵測部落格圖示...",
"ProgressDetectingWeblogSettings":"正在偵測部落格設定...",
"ProgressDeterminingType":"正在判斷 {0} 的類型...",
"ProgressDialogTitle":"進度對話方塊",
"ProgressDownloadFinished":"下載完成",
"ProgressDownloading":"正在下載 {0}...",
"ProgressDownloadingEditingTemplate":"正在下載編輯範本...",
"ProgressDownloadingSupportingFiles":"正在下載支援檔案...",
"ProgressDownloadingWeblogEditingStyle":"正在下載部落格編輯佈景主題...",
"ProgressDownloadingWeblogEditingStyleDeep":"首頁上沒有文章內容，正在檢查文章...",
"ProgressFinalizingEditingTemplateConfig":"正在完成編輯範本設定...",
"ProgressPreparingListOfFiles":"正在準備下載檔案清單...",
"ProgressSaving":"正在儲存 {0}...",
"ProgressStartingDownloadOfReferences":"正在開始下載參考資料...",
"ProgressVerifyingInterface":"正在驗證部落格發佈介面...",
"PropertiesAuthor":"作者(&A)：",
"PropertiesAuthorsFetchingText":"作者清單",
"PropertiesCategories":"類別(&C)：",
"PropertiesCommaSeparated":"(以逗號分隔)",
"PropertiesCommentPolicyClosed":"已關閉",
"PropertiesCommentPolicyNone":"無",
"PropertiesCommentPolicyOpen":"開放",
"PropertiesComments":"留言(&M)：",
"PropertiesDefault":"(預設)",
"PropertiesExcerpt":"摘要(&E)：",
"PropertiesKeywords":"關鍵字(&K)：",
"PropertiesNoPageParent":"(無上層頁面)",
"PropertiesPageOrder":"頁面順序(&O)：",
"PropertiesPageParent":"上層頁面(&P)：",
"PropertiesPanel":"文章屬性",
"PropertiesPassword":"密碼(&W)：",
"PropertiesPings":"Ping(&I)：",
"PropertiesPublishDate":"發佈日期(&U)：",
"PropertiesShowHide":"關閉/開啟屬性面板",
"PropertiesSlug":"代稱(&S)：",
"PropertiesTags":"標籤(&T)：",
"PropertiesTrackbackPolicyAllow":"允許",
"PropertiesTrackbackPolicyDeny":"拒絕",
"PropertiesTrackbacks":"引用網址(&R)：",
"ProxyPrefCustom":"自訂 Proxy 設定",
"ProxyPrefEnabled":"手動設定(&M)",
"ProxyPrefName":"網路 Proxy",
"ProxyPrefPassword":"密碼(&W)：",
"ProxyPrefPort":"連接埠(&P)：",
"ProxyPrefServer":"Proxy 伺服器位址(&R)：",
"ProxyPrefTitle":"網路 Proxy 偏好設定",
"ProxyPrefUsername":"使用者名稱(&N)：",
"PublishDatePrompt":"設定文章日期",
"PublishDateTooltip":"文章日期",
"PublishedNameFormat":"已發佈的 {0}",
"PublishFolderPickerCaption":"選取要發佈的資料夾：",
"PublishFolderPickerTitle":"瀏覽資料夾",
"PublishFolderPickerToolTip":"瀏覽資料夾",
"PublishNow":"立即發佈",
"PushpinAdd":"新增圖釘",
"PushpinEdit":"編輯圖釘",
"PushpinMoreInfoUrl":"更多資訊的網址(&W)：",
"PushpinNotes":"備註(&N)：",
"PushpinPhotoUrl":"相片網址(&P)：",
"PushpinTitle":"標題(&T)：",
"PushpinUntitled":"輸入此圖釘的名稱",
"PushpinValidationError":"目前找不到您輸入的圖釘位置。\n\n您仍要將此網址設為您的自訂圖釘嗎？",
"RecentDrafts":"最近的草稿",
"RecentlyPosted":"最近發佈的文章",
"RecentPostNotSyncCaption":"無法從伺服器擷取 {0}",
"RecentPostNotSyncText":"{0} 無法從部落格伺服器擷取最新的 {1}（發生錯誤或擷取已取消）。",
"RecentPostNotSyncText2":"您仍可使用儲存在此電腦上的本機複本來編輯 {0}。但如果您已在線上變更 {0}，您正在編輯的複本可能已過時。",
"RecentPostNotSyncTitle":"無法從伺服器擷取 {0}",
"RecentPosts":"最近的文章",
"RememberPassword":"記住我的密碼(&R)",
"Retrieving":"正在擷取 {0}",
"RetrievingFromWeblog":"正在從部落格擷取 {0}...",
"RetrySignin":"解決問題後，請再試一次登入。",
"RowPropertiesFixedHeight":"固定高度(&F)：",
"RowPropertiesSizeToContent":"自動調整為內容大小(&A)",
"RowPropertiesTitle":"列屬性",
"SaveButton":"儲存(&S)",
"SeeSolutionOnline":"在線上查看解決方案",
"Selected":"已選取",
"SelectWeblogProvider":"(選取部落格提供者)",
"SemanticHtmlPreviewText":"AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz",
"SendingPing":"正在傳送 Ping",
"SendingPings":"正在傳送 Ping",
"ServiceName":"Live 搜尋地圖",
"ShortcutAlt":"Alt",
"ShortcutCtrl":"Ctrl",
"ShortcutPlus":"+",
"ShortcutShift":"Shift",
"ShowAllPosts":"全部",
"ShowLogFile":"顯示記錄檔",
"ShowProperties":"顯示屬性",
"ShowRealTimeWordCount":"在狀態列中顯示即時字數(&B)",
"ShowXPosts":"{0}",
"SidebarPanel":"工作窗格",
"Size":"大小",
"SpellAdd":"新增(&D)",
"SpellCaps":"大小寫：",
"SpellChange":"變更為(&H)：",
"SpellChangeAll":"全部變更(&L)",
"SpellChangeWord":"變更(&C)",
"SpellIgnore":"略過(&G)",
"SpellIgnoreAll":"全部略過(&I)",
"SpellingPrefAuto":"自動更正常見的大小寫與拼字錯誤(&C)",
"SpellingPrefGroup":"拼字表單選項",
"SpellingPrefName":"拼字",
"SpellingPrefOptions":"一般選項",
"SpellingPrefPub":"發佈前檢查拼字(&P)",
"SpellingPrefReal":"使用即時拼字檢查（波浪底線）(&R)",
"SpellNoSuggest":"(沒有建議)",
"SpellNotInDict":"不在字典中(&N)：",
"SpellOptions":"建議(&U)：",
"SpellSuggest":"建議(&S)",
"SpellText":"檢查拼字",
"SpinnerPixelFormatString":"px",
"SpinnerPixelRepresentativeString":"999 px",
"SplashScreenCopyrightNotice":"Copyright © .NET Foundation. All rights reserved.",
"SplitterMore":"更多...",
"SSGBuildErrorText":"{0} 無法建置您的網站。請確認您的網站可以手動建置，檢查您的建置命令，然後再試一次。\n\n建置命令結束碼：{1}\n命令 STDOUT：\n{2}\n命令 STDERR：\n{3}",
"SSGBuildErrorTitle":"靜態網站建置失敗",
"SSGConfigAuthoringDraftsPath":"草稿路徑：（相對路徑）",
"SSGConfigAuthoringEnableDrafts":"啟用草稿(&D)",
"SSGConfigAuthoringEnableImages":"啟用圖片(&I)",
"SSGConfigAuthoringEnablePages":"啟用頁面(&A)",
"SSGConfigAuthoringImagesGroup":"圖片",
"SSGConfigAuthoringImagesPath":"圖片路徑：（相對路徑）",
"SSGConfigAuthoringPagesGroup":"頁面",
"SSGConfigAuthoringPagesInRoot":"頁面儲存於專案根目錄",
"SSGConfigAuthoringPagesPath":"頁面路徑：（相對路徑）",
"SSGConfigAuthoringPostsDraftsGroup":"文章與草稿",
"SSGConfigAuthoringPostsPath":"文章路徑：（相對路徑）(&P)",
"SSGConfigAuthoringTitle":"撰寫",
"SSGConfigBuildPublishBuildCommand":"建置命令：",
"SSGConfigBuildPublishBuildingGroup":"建置",
"SSGConfigBuildPublishCmdTimeout":"命令逾時（毫秒）(&C)：",
"SSGConfigBuildPublishEnableBuilding":"啟用建置(&B)",
"SSGConfigBuildPublishEnableCmdTimeout":"啟用命令逾時(&E)",
"SSGConfigBuildPublishGeneralGroup":"一般",
"SSGConfigBuildPublishOutputPath":"網站輸出路徑：（相對路徑）",
"SSGConfigBuildPublishPublishCommand":"發佈命令(&P)：",
"SSGConfigBuildPublishPublishingGroup":"發佈",
"SSGConfigBuildPublishShowCmdWindows":"顯示命令視窗(&S)",
"SSGConfigBuildPublishTitle":"建置與發佈",
"SSGConfigFrontMatterKeyCol":"前置資料索引鍵",
"SSGConfigFrontMatterPropertyCol":"屬性",
"SSGConfigFrontMatterReset":"重設為預設值(&R)",
"SSGConfigFrontMatterSubtitle":"您可以在下方調整文章前置資料索引鍵，以符合您的靜態網站產生器。",
"SSGConfigFrontMatterTitle":"前置資料",
"SSGConfigGeneralDetectButton":"執行自動偵測(&D)",
"SSGConfigGeneralDetectLabel":"Open Live Writer 也可以重新嘗試偵測靜態網站的相關設定選項。這可能無法產生完整的設定，因此請使用後續頁面上的欄位確認所有設定均已正確設定。",
"SSGConfigGeneralLocalSitePath":"本機網站路徑(&L)：",
"SSGConfigGeneralOptionsGroup":"選項",
"SSGConfigGeneralSetupGroup":"設定",
"SSGConfigGeneralSiteTitle":"網站標題(&T)：",
"SSGConfigGeneralSiteUrl":"網站 URL(&U)：",
"SSGConfigGeneralTitle":"一般",
"SSGConfigGeneralWizardButton":"執行帳號精靈(&W)",
"SSGConfigGeneralWizardLabel":"如果您希望透過互動方式進行核心靜態網站設定，可以選擇再次執行帳號精靈。",
"SSGConfigTitle":"'{0}' 的靜態網站設定",
"SSGErrorBuildCommandEmptyText":"啟用本機網站建置時，需要提供建置命令。",
"SSGErrorBuildCommandEmptyTitle":"建置命令為空白",
"SSGErrorCommandTimeoutText":"部落格命令已逾時。請檢查您的命令，或延長命令逾時時間。",
"SSGErrorCommandTimeoutTitle":"命令執行逾時",
"SSGErrorItemLoadTextFM":"無法讀取項目前置資料。",
"SSGErrorItemLoadTextId":"項目沒有 ID。",
"SSGErrorItemLoadTitle":"項目載入錯誤",
"SSGErrorPageDoesNotExistText":"找不到具有指定 ID 的頁面。",
"SSGErrorPageDoesNotExistTitle":"頁面不存在",
"SSGErrorPathDraftsEmpty":"草稿路徑為空白。",
"SSGErrorPathDraftsNotFound":"草稿路徑 '{0}' 不存在。",
"SSGErrorPathFolderNotFound":"找不到資料夾",
"SSGErrorPathImagesEmpty":"圖片路徑為空白。",
"SSGErrorPathImagesNotFound":"圖片路徑 '{0}' 不存在。",
"SSGErrorPathLocalSitePathNotFound":"本機網站路徑 '{0}' 不存在。",
"SSGErrorPathOutputEmpty":"輸出路徑為空白。",
"SSGErrorPathOutputNotFound":"輸出路徑 '{0}' 不存在。",
"SSGErrorPathPagesEmpty":"頁面路徑為空白。",
"SSGErrorPathPagesNotFound":"頁面路徑 '{0}' 不存在。",
"SSGErrorPathPostsEmpty":"文章路徑為空白。",
"SSGErrorPathPostsNotFound":"文章路徑 '{0}' 不存在。",
"SSGErrorPostDoesNotExistText":"找不到具有指定 ID 的文章。",
"SSGErrorPostDoesNotExistTitle":"文章不存在",
"SSGErrorPublishCommandEmptyText":"需要提供發佈命令。",
"SSGErrorPublishCommandEmptyTitle":"發佈命令為空白",
"SSGFrontMatterDate":"日期",
"SSGFrontMatterId":"ID",
"SSGFrontMatterLayout":"版面配置",
"SSGFrontMatterParentId":"上層 ID",
"SSGFrontMatterPermalink":"固定連結",
"SSGFrontMatterTags":"標籤",
"SSGFrontMatterTitle":"標題",
"SSGPublishErrorText":"{0} 無法發佈您的網站。請檢查您的網站發佈命令。\n\n發佈命令結束碼：{1}\n命令 STDOUT：\n{2}\n命令 STDERR：\n{3}",
"SSGPublishErrorTitle":"靜態網站發佈失敗",
"Statistics":"統計資料",
"StatisticsSelection":"選取範圍統計資料",
"StatusAutoSaving":"自動儲存中...",
"StatusDraftSaved":"草稿 - 已於 {0} 儲存",
"StatusDraftUnsaved":"草稿 - 未儲存",
"StatusPublished":"已發佈：{0}",
"StatusWeblogNameFormatter":"{0} ({1})",
"SwitchWeblogs":"切換至部落格",
"TableAlignHorizontal":"水平對齊(&H)：",
"TableAlignHorizontalCenter":"置中",
"TableAlignHorizontalLeft":"靠左",
"TableAlignHorizontalRight":"靠右",
"TableAlignVertical":"垂直對齊(&V)：",
"TableAlignVerticalBottom":"靠下",
"TableAlignVerticalMiddle":"置中",
"TableAlignVerticalTop":"靠上",
"TableBorder":"框線",
"TableCellPadding":"儲存格填補",
"TableCellPaddingLabel":"填補儲存格內容(&P)：",
"TableCellSpacing":"儲存格間距",
"TableCellSpacingLabel":"儲存格間距(&S)：",
"TableColumns":"欄",
"TableColumnsLabel":"欄數(&C)：",
"TableRows":"列",
"TableRowsLabel":"列數(&R)：",
"TableShowBorderLabel":"顯示表格框線(&B)：",
"TableTableProperties":"表格屬性",
"TagControlSetTags":"設定標籤（以逗號分隔）",
"Tags":"標籤",
"TagsCaptionFormat":"{0} 標籤：{tag-group}",
"TagsCreateNew":"建立新標籤提供者",
"TagsCustomizeProviders":"(自訂提供者...)",
"TagsEditPattern":"編輯 {0}",
"TagsHtmlCaptionHelpString":"將與標籤 HTML 一起顯示的 HTML 說明文字。在您希望放置 HTML 標籤範本所產生之 HTML 的位置使用 {0}。",
"TagsHtmlCaptionLabel":"標籤清單的 HTML 說明文字(&C)：",
"TagsHtmlDelimiterHelpString":"應顯示在標籤 HTML 之間的分隔符號。分隔符號將顯示在每個標籤所產生的 HTML 之間。",
"TagsHtmlDelimiterLabel":"每個標籤的 HTML 分隔符號(&S)：",
"TagsHtmlPreviewHelpString":"針對一組標籤將產生之原始 HTML 的預覽。",
"TagsHtmlPreviewLabel":"HTML 預覽：",
"TagsHtmlTemplateHelpString":"HTML 範本將用來為每個提供的標籤產生 HTML。在 HTML 範本中，在應放置標籤的位置使用 {0}，在應放置 URL 編碼標籤的位置使用 {1}。",
"TagsHtmlTemplateLabel":"每個標籤的 HTML 範本(&H)：",
"TagsInsertTags":"插入標籤",
"TagsProviderDefaultCaption":"{0} 標籤：{1}",
"TagsProviderNameHelpString":"標籤提供者的名稱。插入標籤時，此名稱將顯示在標籤提供者清單中。",
"TagsProviderNameLabel":"提供者名稱(&P)：",
"TagsRestoreDefaults":"還原預設值(&R)",
"TagsTagExample1":"標籤 1",
"TagsTagExample2":"標籤 2",
"TagsTagOptions":"標籤選項",
"TagsTagProviderLabel":"標籤提供者(&P)：",
"TagsTagProvidersLabel":"標籤提供者(&T)：",
"TagsTagsLabel":"標籤（以逗號分隔）(&T)：",
"TagsXmlParsingError":"缺少 {0} 參數",
"TemporaryPostBody":"這是一篇未被刪除的暫時文章。請手動刪除。（{0} - {1}）",
"TemporaryPostTitle":"用於佈景主題偵測的暫時文章（{0} - {1}）",
"TextStyle":"文字樣式",
"TheErrorOccuredBecause":"發生此錯誤的原因如下：",
"TiltEditorLabel":"傾斜(&T)：",
"TiltEditorTitle":"傾斜",
"TitleDefaultText":"輸入 {0} 標題",
"TitleRemindDontShowAgain":"不再提醒我缺少標題(&D)",
"TitleRemindError":"未指定 {0} 標題",
"TitleRemindExplanation":"您尚未為此 {0} 指定標題。您仍要繼續發佈嗎？",
"TitleRemindTitle":"標題提醒",
"Today":"今天",
"ToolbarBoldLetter":"B",
"ToolbarFontStyleFontFamily":"",
"ToolbarItalicLetter":"I",
"ToolbarStrikethroughLetter":"A",
"ToolbarUnderlineLetter":"U",
"TruncatedString":"{0}...",
"UnexpectedErrorClickHere":"按一下這裡以查看錯誤詳細資料",
"UnexpectedErrorContinue":"繼續(&C)",
"UnexpectedErrorDescription":"我們已建立一份您可以檢視的錯誤摘要。",
"UnexpectedErrorExit":"結束",
"UnexpectedErrorPluginDescription":"{0} 外掛程式中發生錯誤：\n\n{1}",
"UnexpectedErrorPluginTitle":"發生外掛程式錯誤",
"UnexpectedErrorSendError":"傳送錯誤報告(&S)",
"UnexpectedErrorTitle":"未預期的錯誤",
"UnhandledExceptionErrorMessage":"應用程式內發生未預期的錯誤。",
"UnhandledExceptionErrorTitle":"發生未預期的錯誤",
"Unknown":"未知",
"Untitled":"未命名",
"UntitledPage":"(未命名的頁面)",
"UntitledPost":"(未命名的文章)",
"UpdateAccountConfiguration":"更新帳號資訊(&U)...",
"UpdateAccountConfigurationTitle":"更新帳號設定",
"UpdatesAvailableAskLaterButton":"稍後再詢問我(&S)",
"UpdatesAvailableChecking":"正在檢查更新",
"UpdatesAvailableDownloadButton":"立即下載(&D)",
"UpdatesAvailableLink":"更多資訊",
"UpdatesAvailableMessage":"必要的更新將在您下次啟動 Open Live Writer 時套用。",
"UpdatesAvailableMessageFull":"{0} 的新版本現已推出。按一下「立即下載」按鈕以下載並安裝更新。",
"UpdatesAvailableMessagePrerelease":"{0} 的新預發行版本現已推出。按一下「立即下載」按鈕以下載並安裝更新。",
"UpdatesAvailableNofifyBeta":"同時檢查預發行（Beta）版本(&V)",
"UpdatesAvailableNotify":"自動檢查更新(&A)",
"UpdatesAvailableNoUpdateText":"沒有可用的更新。您目前執行的是最新版 {0}。",
"UpdatesAvailableNoUpdateTitle":"沒有可用的更新",
"UpdatesAvailableTitle":"有新版本可供使用",
"UpdatesAvailableTitlePrerelease":"有新的預發行版本可供使用",
"UpdatesBandClose":"關閉",
"UpdatesInstalling":"正在下載並安裝 {0} 個更新。請稍候...",
"UpdatesPreparing":"正在準備更新 Open Live Writer...",
"UpdatesProgressTitle":"安裝更新 - Open Live Writer",
"UpdatesStartingWriter":"正在啟動已更新的 Open Live Writer...",
"UpdateWeblogDraft":"草稿",
"UpdateWeblogPublish1":"正在發佈您的 {0}",
"UpdateWeblogPublish2":"正在將 {0} 發佈至 {1}",
"UpdateWeblogViewPost":"發佈後在瀏覽器中開啟我的部落格",
"UrlLabel":"網址(&W)：",
"UrlRetrieveProgressCaption":"正在擷取資料",
"UrlRetrieveProgressMessage":"正在擷取發佈所需的其他資料...",
"Username":"使用者名稱：",
"UsernameLabel":"使用者名稱(&U)：",
"VideoCaptionDefaultText":"在此輸入影片說明文字",
"VideoCaptionMaxCharactersAccepted":"245",
"VideoError":"發佈影片時發生錯誤",
"VideoErrorTryAgain":"請移除影片後再試一次發佈。",
"VideoFromVideoService":"從影片服務",
"VideoGetVideosError":"取得影片清單時發生錯誤。",
"VideoLoading":"載入中...",
"VideoLocalProcessing":"正在上傳影片...",
"VideoNetworkError":"網路連線發生錯誤。",
"VideoRemoteProcessing":"{0} 正在處理您上傳的影片。\n這可能需要一些時間。",
"VideoUrlConvertError":"此影片不包含影片 ID。請輸入影片的內嵌碼。",
"ViewAll":"檢視全部",
"ViewButton":"檢視(&V)",
"ViewMap":"檢視地圖",
"ViewWeblog":"檢視部落格",
"ViewWeblogCapabilities":"查看部落格功能",
"WatermarkAlignBottomLeft":"左下",
"WatermarkAlignBottomRight":"右下",
"WatermarkAlignCentered":"置中",
"WatermarkAlignTopLeft":"左上",
"WatermarkAlignTopRight":"右上",
"WatermarkAlignUnknown":"未知",
"WatermarkDefaultFont":"Arial",
"WatermarkDefaultText":"© {0:yyyy}",
"WatermarkDialogTitle":"浮水印",
"WatermarkFontFamilyLabel":"字型系列(&F)：",
"WatermarkPositionLabel":"位置(&P)：",
"WatermarkSizeLabel":"大小(&S)：",
"WatermarkTextLabel":"浮水印文字(&W)：",
"WatsonMainIntroBoldFormat":"{0} 發生問題：{1}。",
"WatsonMainIntroRegFormat":"{0} {1}",
"WatsonMainPleaBold":"請告知 Microsoft 此問題。",
"WatsonMainPleaReg":"我們已建立一份您可以傳送的錯誤報告，以協助我們修正錯誤。我們將以機密且匿名的方式處理此報告。",
"WatsonNoReportButton":"不要傳送報告",
"WatsonReportButton":"傳送報告",
"WebLayoutWarning1":"使用目前部落格的佈景主題編輯內容時可能會遇到問題（例如，文章版面配置不正確或選取及調整內容大小時出現問題）。",
"WebLayoutWarning2":"如果確實遇到問題，請切換回不使用佈景主題的編輯模式。",
"WebLayoutWarningTitle":"網頁版面配置檢視",
"Weblog":"部落格",
"WeblogCapabilitiesCapability":"功能",
"WeblogCapabilitiesCaption":"{0} 已偵測到您部落格的以下功能：",
"WeblogCapabilitiesTitle":"部落格功能",
"WeblogCapabilitiesValue":"值",
"WeblogName":"部落格名稱(&B)：",
"WeblogNameColon":"部落格暱稱(&N)：",
"WeblogProvider":"部落格服務：",
"WeblogSettings":"部落格選項 - {0}",
"Width":"寬度",
"WidthColon":"寬度(&W)：",
"WidthLabel":"寬度(&W)：",
"WindowTitleFormat":"{0} - {1}",
"WithEllipses":"{0}...",
"WizardBack":"< 上一步(&B)",
"WizardBlogTypeConfigureTo":"設定 {0} 以發佈至：",
"WizardBlogTypeGoogleBlogger":"Google Blogger(&G)",
"WizardBlogTypeOther":"其他服務(&O)",
"WizardBlogTypeSharePoint":"SharePoint(&S)",
"WizardBlogTypeStaticSite":"靜態網站產生器(&E)",
"WizardBlogTypeWelcome":"許多熱門的部落格服務都支援 {0}。",
"WizardBlogTypeWhatBlogType":"您使用哪種部落格服務？",
"WizardFinish":"完成",
"WizardNext":"下一步(&N) >",
"WordCount":"字數",
"WordCountTitle":"字數統計",
"Words":"字數：{0}",
"Yes":"是",
"YesButton":"是(&Y)",
"YouTubeblocked":"影片已被內容擁有者封鎖。",
"YouTubecantProcess":"YouTube 無法轉換影片檔案。",
"YouTubecopyright":"影片侵犯著作權。",
"YouTubeduplicate":"影片與另一個已上傳的影片重複。",
"YouTubeempty":"上傳的檔案為空白。",
"YouTubeinappropriate":"影片包含不當內容。",
"YouTubeinvalidFormat":"上傳的影片格式無效。",
"YouTubeInvalidResult":"收到來自 YouTube 的未預期回應。",
"YouTubeNoAccount":"此 Google 帳號沒有關聯的 YouTube 帳號。",
"YouTubesuspended":"與此影片相關聯的帳號已被停用。",
"YouTubetermsOfUse":"影片違反使用條款。",
"YouTubetooLong":"影片超過最長 10 分鐘的時間限制。",
"YouTubetooSmall":"上傳的檔案太小。",
"YouTubeunsupportedCodec":"影片使用不支援的轉碼器。",
"YouTubeVideoError":"上傳影片時發生未預期的錯誤。",
}

RESX_HEADER = '''<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>'''

def xml_escape(v):
    return v.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')

# Merge: Part1 values are XML-encoded so unescape first, Part2 are plain
translations = {}
for k, v in PART1.items():
    translations[k] = html.unescape(v)
for k, v in PART2.items():
    translations[k] = v  # already plain text

lines = [RESX_HEADER]
for key, val in translations.items():
    val_escaped = xml_escape(val)
    lines.append(f'  <data name="{key}" xml:space="preserve">\n    <value>{val_escaped}</value>\n  </data>')
lines.append('</root>\n')

OUTPUT = r'd:\00-My Projects\OpenLiveWriter\src\managed\OpenLiveWriter.Localization\Strings.zh-TW.resx'
with open(OUTPUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print(f"Done: {len(translations)} entries written to Strings.zh-TW.resx")
